version: '3.8'
services:
  frontend:
    build:
      context: ./app-frontend
    ports:
      - "8080:8080"  
    volumes:
      - ./problems:/app/problems  
    environment:
      - NODE_ENV=production  
    
  backend:
    build:
      context: ./code Judge 
    ports:
      - "3000:3000"  
    volumes:
      - ./problems:/app/problems
      - ./code Judge/.env:/app/.env   
    environment:
      - NODE_ENV=production  
    depends_on:
      - frontend
